### ISSUE TITLE
localhost doesnt seem to work

### ISSUE THREAD

**Issue by TaxMachine** [larsgw/sync-fetch#26]
im trying to fetch data to a local express server for testing and i get this error
```
FetchError: request to https://0.0.0.0:9000/dual failed, reason: write EPROTO 140361671825344:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:331:
```

**Comment by larsgw** [comment]
Does it work with http instead of https?

**Comment by TaxMachine** [comment]
ong i didnt saw i wrote https :skull: but ty for pointing me this out.(i haven't slept for some days mb)

**Comment by larsgw** [comment]
No problem!
