### ISSUE TITLE
Logging response in the console. Is it possible to suppress it as it is using disk space and unwanted use of resources?

### ISSUE THREAD

**Issue by jeet1212** [larsgw/sync-fetch#30]
I would like to use in the production but unable to use it as it is logging the whole response in the console.

is it any way to return response without console.log as below in the worker.js ?

function respond (message) {
  console.log(JSON.stringify(message))
}

![image](https://user-images.githubusercontent.com/1590247/190899638-b78c33ed-0b07-47c8-af8b-aba4ed924035.png)

**Comment by larsgw** [comment]
It needs to pass information from one process to the other through standard out (which is why it is logged, I could also just use `process.stdout.write()` directly). However, this, especially the body, could be done in a streaming manner which would probably be better for performance.

**Comment by jeet1212** [comment]
Thank you @larsgw for considering it as enhancement! 
Are you planning this enhancement to implement soon?

**Comment by larsgw** [comment]
I think streaming the body doesn't really matter actually, but I did change to `process.stdout.write()` in v0.4.2. Hope it helps.

**Comment by jeet1212** [comment]
Thank you!
