### ISSUE TITLE
request[1].body = shared.parseBody(init.body).toString() breaks binary encoding

### ISSUE THREAD

**Issue by gfic-limited** [larsgw/sync-fetch#37]
With binary payload bodies, the toString () breaks the encoding. Unsure of what the purpose of this functionality is, but I expected issues on REST API transfers to Google Cloud Storage and narrowed it down to this code which was damaging the encoding of a binary zip file.

**Comment by larsgw** [comment]
The purpose is that the entire request is currently serialized as JSON, but that is not necessarily a requirement. I will look into alternatives.

**Comment by gfic-limited** [comment]
Thanks. I have a reasonably sized code base that started under Apps Script using UrlFetchApp.fetch and now also runs on Node CLI and CloudRun. I use sync-fetch in the cross-platform layer for non Apps Script environments, since Apps Script and its support functions, are synchronous. All had been working fine for JSON and non-binary payloads, but recently started sending binary content into Cloud Storage and issue appeared.

**Comment by gfic-limited** [comment]
I ended up with this, removing the need for the package stripping it
down to just what I need (I'm sure it can be stripped further, but
this is good enough for now) and it works for me (maybe still some
bugs in there!) in my hybrid environment (apps script will self-build
docker containers and run them in the cloud, so
__gcloudrun_contentsAdd does this). Thanks for the original version.


// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function __sync_fetch_runner () {
  const chunks = Array ();
  process.stdin.resume ();
  process.stdin.setEncoding ('utf8');
  process.stdin.on ('data', (chunk) => chunks.push (chunk));
  process.stdin.on ('end', () => {
    const __error = ({ constructor, message, type, code }) => [
constructor.name, [message, type, { code }] ];
    const __content = (content) => Buffer.from (content).toString ('base64');
    const __buffer = (buffer) => { const buff = new ArrayBuffer
(buffer.length), view = new Uint8Array (buff); for (var i = 0; i <
buffer.length; ++i) view [i] = buffer [i]; return buff; }
    const __request = (resource, init) => new Request (resource, {
...init, body: init.body ? __buffer (Buffer.from (init.body,
'base64')) : undefined });
    const __response = ({ url, status, statusText, redirected, headers
}) => ({ url, status, statusText, redirected, headers:
Object.fromEntries (headers.entries ()) });
    const recv_request = (input) => __request (...JSON.parse (input));
    const send_respond = (response) => process.stdout.write
(JSON.stringify (response));
    fetch (recv_request (chunks.join ('')))
      .then (response => response.arrayBuffer ()
        .then (buffer => send_respond ([__content (buffer), __response
(response)]))
        .catch (error => send_respond (['', __response (response),
__error (error)])))
      .catch (error => send_respond (__error (error)));
  });
}
__gcloudrun_contentsAdd ('__fetch_runner.js',
'application/javascript', () => __sync_fetch_runner.toString () + ';
__sync_fetch_runner ();');

/* CODE:GCLOUD

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function sync_fetch (resource, init) {
  const __execute = require ('child_process').execFileSync;
  const __running = [ [__dirname, '__fetch_runner.js'].join ('/') ];
  const __process = (input) => __execute (process.execPath, __running,
{ windowsHide: true, maxBuffer: Infinity, input, shell: false
}).toString ();

  const __process_body = (body) => Body.__parse (body).toString ('base64');
  const __process_head = (head) => Object.fromEntries ((new Headers
(head)).entries ());

  const request = [resource, { }]; Object.assign (request [1], init);
  if (request [1].body) request [1].body = __process_body (request [1].body);
  if (request [1].headers) request [1].headers = __process_head
(request [1].headers);

  const response = JSON.parse (__process (JSON.stringify (request)));
  if (!('headers' in response [1]))
    throw SyncFetchError.__deserialize (...response);
  return SyncFetchResponse.__deserialize (...response);
}

// -----------------------------------------------------------------------------------------------------------------------------------------

class SyncFetchError extends Error {
  constructor (details) { super (details); }
  static __deserialize (name, init) { const errors = { TypeError }
    return (name in errors) ? new errors [name] (...init) : new
SyncFetchError (...init); }
}

const SyncFetchStream = require ('stream');

class SyncFetchResponse extends require ('node-fetch').Response {
  static __serialize (response) {
    const { url, headers, status, statusText, redirected } = response;
return { url, headers, status, statusText, redirected }; }
  static __deserialize (body, init, bodyError) { const buffer =
Buffer.from (body, 'base64');
    const __headers = (p = {}) => { const h = new Headers (); for
(const n in p) for (const v of p [n]) h.append (n, v); return h; }
    return new SyncFetchResponse (SyncFetchResponse.__createStream
(body ? buffer : null), { ...init, headers: __headers (init.headers)
}, { buffer, bodyError }); }
  static __createStream (buffer) {
    return new SyncFetchStream.Transform ({ read () { this.push
(buffer); this.push (null); } }); }

  constructor (body, init, options = {}) { super (body, init);
    const { buffer = Body.__parse (body), bodyError } = options;
    Object.defineProperty (this, 'bodyBuffer', { value: buffer,
enumerable: false });
    if (bodyError) Object.defineProperty (this, 'bodyError', { value:
SyncFetchError.__deserialize (...bodyError), enumerable: false });
  }
  clone () { Body.__check (this); const buffer = Buffer.from (this.bodyBuffer);
    return new SyncFetchResponse (SyncFetchResponse.__createStream
(buffer), SyncFetchResponse.__serialize (this), { buffer, bodyError:
this.bodyError });
  }
}

class Body {
  static __parse (body) {
    if (body == null) return null;
    if (Buffer.isBuffer (body)) return body;
    if (Object.prototype.toString.call (body) === '[object
ArrayBuffer]') return Buffer.from (body);
    if (ArrayBuffer.isView (body)) return Buffer.from (body.buffer,
body.byteOffset, body.byteLength);
    if (typeof body == 'string') return Buffer.from (String (body));
    throw new TypeError (`sync_fetch does not support bodies of type: ${type}`);
  }
  static __check (body) {
    if (body.bodyError) throw body.bodyError;
    if (body.bodyUsed) throw new TypeError (`body used already for:
${body.url}`); }
  static __consume (body) {
    Object.getPrototypeOf (Object.getPrototypeOf (body))
['buffer'].bind (body) ().catch (error => console.error (error));
    return body.bodyBuffer || Buffer.alloc (0); }
  static __mixin (proto) { for (const name of
Object.getOwnPropertyNames (Body.prototype)) if (name !==
'constructor')
    Object.defineProperty (proto, name, {
...Object.getOwnPropertyDescriptor (Body.prototype, name), enumerable:
true }); }

  arrayBuffer () { Body.__check (this); const buf = Body.__consume
(this); return buf.buffer.slice (buf.byteOffset, buf.byteOffset +
buf.byteLength); }
  text () { Body.__check (this); return Body.__consume (this).toString (); }
  json () { Body.__check  (this); try { return JSON.parse
(Body.__consume (this).toString ()); }
    catch (err) { throw new SyncFetchError (`invalid json response
body at ${this.url}: ${err.message}`); } }
  buffer () { Body.__check  (this); return Buffer.from (Body.__consume
(this)); }
}

Body.__mixin (SyncFetchResponse.prototype);
Object.defineProperties (SyncFetchResponse.prototype, { clone: {
enumerable: true } });

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

CODE:GCLOUD */

**Comment by gfic-limited** [comment]
OK, attached as the last version now that I have checked it into my own codebase

On Thu, 8 Jun 2023 at 16:42, Lars Willighagen ***@***.***> wrote:
>
> The purpose is that the entire request is currently serialized as JSON, but that is not necessarily a requirement. I will look into alternatives.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>


// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function util_obj_property_mixin (From, To) { for (const name of Object.getOwnPropertyNames (From.prototype)) if (name !== 'constructor')
  Object.defineProperty (To.prototype, name, { ...Object.getOwnPropertyDescriptor (From.prototype, name), enumerable: true }); }
function util_obj_property_enunerable (Class, prop, value) {
  Object.defineProperties (Class.prototype, { [prop]: { enumerable: value } });
}

// -----------------------------------------------------------------------------------------------------------------------------------------

function __sync_fetch_runner () {
  const chunks = Array ();
  process.stdin.resume ();
  process.stdin.setEncoding ('utf8');
  process.stdin.on ('data', (chunk) => chunks.push (chunk));
  process.stdin.on ('end', () => {
    const __error = ({ constructor, message, type, code }) => [ constructor.name, [message, type, { code }] ];
    const __content = (content) => Buffer.from (content).toString ('base64');
    const __buffer = (buffer) => { const buff = new ArrayBuffer (buffer.length), view = new Uint8Array (buff); for (var i = 0; i < buffer.length; ++i) view [i] = buffer [i]; return buff; }
    const __request = (resource, init) => new Request (resource, { ...init, body: init.body ? __buffer (Buffer.from (init.body, 'base64')) : undefined });
    const __response = ({ url, status, statusText, redirected, headers }) => ({ url, status, statusText, redirected, headers: Object.fromEntries (headers.entries ()) });
    const recv_request = (input) => __request (...JSON.parse (input));
    const send_respond = (response) => process.stdout.write (JSON.stringify (response));
    fetch (recv_request (chunks.join ('')))
      .then (response => response.arrayBuffer ()
        .then (buffer => send_respond ([__content (buffer), __response (response)]))
        .catch (error => send_respond (['', __response (response), __error (error)])))
      .catch (error => send_respond (__error (error)));
  });
}
__gcloudrun_contentsAdd ('__fetch_runner.js', 'application/javascript', () => __sync_fetch_runner.toString () + '; __sync_fetch_runner ();');

/* CODE:GCLOUD

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function sync_fetch (resource, init) {
  const __execute = require ('child_process').execFileSync;
  const __running = [ [__dirname, '__fetch_runner.js'].join ('/') ];
  const __process = (input) => __execute (process.execPath, __running, { windowsHide: true, maxBuffer: Infinity, input, shell: false }).toString ();

  const __process_body = (body) => SyncFetchBody.__parse (body).toString ('base64');
  const __process_head = (head) => Object.fromEntries ((new Headers (head)).entries ());

  const request = [resource, { }]; Object.assign (request [1], init);
  if (request [1].body) request [1].body = __process_body (request [1].body);
  if (request [1].headers) request [1].headers = __process_head (request [1].headers);

  const response = JSON.parse (__process (JSON.stringify (request)));
  if (!('headers' in response [1]))
    throw SyncFetchError.__deserialize (...response);
  return SyncFetchResponse.__deserialize (...response);
}

// -----------------------------------------------------------------------------------------------------------------------------------------

class SyncFetchError extends Error {
  static __deserialize (name, init) {
    const errors = { TypeError }; return (name in errors) ? new errors [name] (...init) : new SyncFetchError (...init); }

  constructor (details) { super (details); }
}

const SyncFetchStream = require ('stream');

class SyncFetchResponse extends require ('node-fetch').Response {
  static __serialize (response) {
    const { url, headers, status, statusText, redirected } = response; return { url, headers, status, statusText, redirected }; }
  static __deserialize (body, init, bodyError) { const buffer = Buffer.from (body, 'base64');
    const __headers = (p = {}) => { const h = new Headers (); for (const n in p) for (const v of p [n]) h.append (n, v); return h; }
    return new SyncFetchResponse (SyncFetchResponse.__streamalize (body ? buffer : null), { ...init, headers: __headers (init.headers) }, { buffer, bodyError }); }
  static __streamalize (buffer) {
    return new SyncFetchStream.Transform ({ read () { this.push (buffer); this.push (null); } }); }

  constructor (body, init, opts = {}) { super (body, init);
    const { buffer = SyncFetchBody.__parse (body), bodyError } = opts;
    Object.defineProperty (this, 'bodyBuffer', { value: buffer, enumerable: false });
    if (bodyError) Object.defineProperty (this, 'bodyError', { value: SyncFetchError.__deserialize (...bodyError), enumerable: false }); }
  clone () { this.__check (); const buffer = Buffer.from (this.bodyBuffer);
    return new SyncFetchResponse (SyncFetchResponse.__streamalize (buffer), SyncFetchResponse.__serialize (this), { buffer, bodyError: this.bodyError });
  }
}

class SyncFetchBody {
  static __parse (body) {
    if (body == null) return null;
    if (Buffer.isBuffer (body)) return body;
    if (Object.prototype.toString.call (body) === '[object ArrayBuffer]') return Buffer.from (body);
    if (ArrayBuffer.isView (body)) return Buffer.from (body.buffer, body.byteOffset, body.byteLength);
    if (typeof body == 'string') return Buffer.from (String (body));
    throw new TypeError (`sync_fetch does not support bodies of type: ${type}`);
  }

  __check () { if (this.bodyError) throw this.bodyError;
    if (this.bodyUsed) throw new TypeError (`body used already for: ${this.url}`); }
  __consume () { Object.getPrototypeOf (Object.getPrototypeOf (this)) ['buffer'].bind (this) ().catch (error => console.error (error));
    return this.bodyBuffer || Buffer.alloc (0); }

  arrayBuffer () { this.__check (); const buf = this.__consume (); return buf.buffer.slice (buf.byteOffset, buf.byteOffset + buf.byteLength); }
  text () { this.__check (); return this.__consume ().toString (); }
  json () { this.__check (); try { return JSON.parse (this.__consume ().toString ()); } catch (err) { throw new SyncFetchError (`invalid json response at ${this.url}: ${err.message}`); } }
  buffer () { this.__check (); return Buffer.from (this.__consume ()); }
}

util_obj_property_mixin (SyncFetchBody, SyncFetchResponse);
util_obj_property_enunerable (SyncFetchResponse, 'clone', true);

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

CODE:GCLOUD */

**Comment by gfic-limited** [comment]
OK this is the stripped down version I created that works for my use case, replacing UrlFetchApp.fetch in a code base that began in Apps Script but now runs in Cloud.



```
/* CODE:GCLOUD

const __connect_fetch = sync_fetch;
const __connect_responseDebugHeaders = (r) => r.headers;
const __connect_responseDebugContent = (r) => r.clone ().text ();
const __connect_responseFetch = (u, o) => { 
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'data') o.headers ['Content-Type'] = 'application/octet-stream';
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'text') o.headers ['Content-Type'] = 'text/plain';
  if (o.payload) o.body = o.payload, delete o.payload; 
  return __connect_fetch (u, o); 
}
const __connect_responseStatus = (r) => r.status;
const __connect_responseCheck = (r) => { if (!r.ok) throw Error (`__connect_error: ${r.status} ${r.statusText}`); }
const __connect_responseDecode = (r, t) => { const f = {
    'arraybuffer': (r) => r.arrayBuffer (),
    'blob': (r) => r.blob (),
    'json': (r) => r.json (),
    'xml' : (r) => __xml_parse (r.text ()),
    'text': (r) => String (r.text ()),
    'data': (r) => new Uint8Array (r.arrayBuffer ())
  } [t]; return f ? f (r) : undefined;
}

function __xml_parse (text) {
  throw 'xml parsing not implemented';
}

/*
CODE:GCLOUD */

const __connect_responseDebugHeaders = (r) => r.getAllHeaders ();
const __connect_responseDebugContent = (r) => r.getContentText ();
const __connect_responseFetch = (u, o) => {
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'data') o.headers ['Content-Type'] = 'application/octet-stream';
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'text') o.headers ['Content-Type'] = 'text/plain';
  return UrlFetchApp.fetch (u, o);
}
const __connect_responseStatus = (r) => r.getResponseCode ();
const __connect_responseCheck = (r) => { }
const __connect_responseDecode = (r, t) => { const f = {
    'arraybuffer': (r) => util_data_to_arraybuffer (r.getBlob ().getBytes ()),
    'blob': (r) => r.getBlob (),
    'json': (r) => JSON.parse (r.getContentText ()),
    'xml' : (r) => __xml_parse (r.getContentText ()),
    'text': (r) => r.getContentText (),
    'data': (r) => r.getContent (),
  } [t]; return f ? f (r) : undefined;
}

function __xml_parse (text) {
  if (text.includes ('<') && text.includes ('>'))
    if (!util_is_null (text = XmlService.parse (text)))
      return text.getRootElement (); // might be undefined
  return undefined;
}

/* CODE:GCLOUD
*/

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function util_obj_property_mixin (From, To) { for (const name of Object.getOwnPropertyNames (From.prototype)) if (name !== 'constructor')
  Object.defineProperty (To.prototype, name, { ...Object.getOwnPropertyDescriptor (From.prototype, name), enumerable: true }); }
function util_obj_property_enunerable (Class, prop, value) {
  Object.defineProperties (Class.prototype, { [prop]: { enumerable: value } });
}

// -----------------------------------------------------------------------------------------------------------------------------------------

function __sync_fetch_runner () {
  const chunks = Array ();
  process.stdin.resume ();
  process.stdin.setEncoding ('utf8');
  process.stdin.on ('data', (chunk) => chunks.push (chunk));
  process.stdin.on ('end', () => {
    const __error = ({ constructor, message, type, code }) => [ constructor.name, [message, type, { code }] ];
    const __content = (content) => Buffer.from (content).toString ('base64');
    const __buffer = (buffer) => { const buff = new ArrayBuffer (buffer.length), view = new Uint8Array (buff); for (var i = 0; i < buffer.length; ++i) view [i] = buffer [i]; return buff; }
    const __request = (resource, init) => new Request (resource, { ...init, body: init.body ? __buffer (Buffer.from (init.body, 'base64')) : undefined });
    const __response = ({ url, status, statusText, redirected, headers }) => ({ url, status, statusText, redirected, headers: Object.fromEntries (headers.entries ()) });
    const recv_request = (input) => __request (...JSON.parse (input));
    const send_respond = (response) => process.stdout.write (JSON.stringify (response));
    fetch (recv_request (chunks.join ('')))
      .then (response => response.arrayBuffer ()
        .then (buffer => send_respond ([__content (buffer), __response (response)]))
        .catch (error => send_respond (['', __response (response), __error (error)])))
      .catch (error => send_respond (__error (error)));
  });
}
__gcloudrun_contentsAdd ('__fetch_runner.js', 'application/javascript', () => __sync_fetch_runner.toString () + '; __sync_fetch_runner ();');

/* CODE:GCLOUD

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function sync_fetch (resource, init) {
  const __execute = require ('child_process').execFileSync;
  const __running = [ [__dirname, '__fetch_runner.js'].join ('/') ];
  const __process = (input) => __execute (process.execPath, __running, { windowsHide: true, maxBuffer: Infinity, input, shell: false }).toString ();

  const __process_body = (body) => SyncFetchBody.__parse (body).toString ('base64');
  const __process_head = (head) => Object.fromEntries ((new Headers (head)).entries ());

  const request = [resource, { }]; Object.assign (request [1], init);
  if (request [1].body) request [1].body = __process_body (request [1].body);
  if (request [1].headers) request [1].headers = __process_head (request [1].headers);

  const response = JSON.parse (__process (JSON.stringify (request)));
  if (!('headers' in response [1]))
    throw SyncFetchError.__deserialize (...response);
  return SyncFetchResponse.__deserialize (...response);
}

// -----------------------------------------------------------------------------------------------------------------------------------------

class SyncFetchError extends Error {
  static __deserialize (name, init) { 
    const errors = { TypeError }; return (name in errors) ? new errors [name] (...init) : new SyncFetchError (...init); }

  constructor (details) { super (details); }
}

const SyncFetchStream = require ('stream');

class SyncFetchResponse extends require ('node-fetch').Response {
  static __serialize (response) {
    const { url, headers, status, statusText, redirected } = response; return { url, headers, status, statusText, redirected }; }
  static __deserialize (body, init, bodyError) { const buffer = Buffer.from (body, 'base64');
    const __headers = (p = {}) => { const h = new Headers (); for (const n in p) for (const v of p [n]) h.append (n, v); return h; }
    return new SyncFetchResponse (SyncFetchResponse.__streamalize (body ? buffer : null), { ...init, headers: __headers (init.headers) }, { buffer, bodyError }); }
  static __streamalize (buffer) {
    return new SyncFetchStream.Transform ({ read () { this.push (buffer); this.push (null); } }); }

  constructor (body, init, opts = {}) { super (body, init);
    const { buffer = SyncFetchBody.__parse (body), bodyError } = opts;
    Object.defineProperty (this, 'bodyBuffer', { value: buffer, enumerable: false });
    if (bodyError) Object.defineProperty (this, 'bodyError', { value: SyncFetchError.__deserialize (...bodyError), enumerable: false }); }
  clone () { this.__check (); const buffer = Buffer.from (this.bodyBuffer);
    return new SyncFetchResponse (SyncFetchResponse.__streamalize (buffer), SyncFetchResponse.__serialize (this), { buffer, bodyError: this.bodyError });
  }
}

class SyncFetchBody {
  static __parse (body) {
    if (body == null) return null;
    if (Buffer.isBuffer (body)) return body;
    if (Object.prototype.toString.call (body) === '[object ArrayBuffer]') return Buffer.from (body);
    if (ArrayBuffer.isView (body)) return Buffer.from (body.buffer, body.byteOffset, body.byteLength);
    if (typeof body == 'string') return Buffer.from (String (body));
    throw new TypeError (`sync_fetch does not support bodies of type: ${type}`);
  }

  __check () { if (this.bodyError) throw this.bodyError;
    if (this.bodyUsed) throw new TypeError (`body used already for: ${this.url}`); }
  __consume () { Object.getPrototypeOf (Object.getPrototypeOf (this)) ['buffer'].bind (this) ().catch (error => console.error (error));
    return this.bodyBuffer || Buffer.alloc (0); }
  
  arrayBuffer () { this.__check (); const buf = this.__consume (); return buf.buffer.slice (buf.byteOffset, buf.byteOffset + buf.byteLength); }
  text () { this.__check (); return this.__consume ().toString (); }
  json () { this.__check (); try { return JSON.parse (this.__consume ().toString ()); } catch (err) { throw new SyncFetchError (`invalid json response at ${this.url}: ${err.message}`); } }
  buffer () { this.__check (); return Buffer.from (this.__consume ()); }
}

util_obj_property_mixin (SyncFetchBody, SyncFetchResponse);
util_obj_property_enunerable (SyncFetchResponse, 'clone', true);

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

CODE:GCLOUD */
```

**Comment by gfic-limited** [comment]
OK this is the stripped down version I created that works for my use case, replacing UrlFetchApp.fetch in a code base that began in Apps Script but now runs in Cloud, and removing any other dependencies (no node-fetch, stream, etc); for a simple use case (see the first part of the code). Putting it here just in case anyone else finds it useful. The main area of improvement might be around the passing of large body data in base64 format through stdout between the processes.

```
/* CODE:GCLOUD

const __connect_fetch = sync_fetch;
const __connect_responseDebugHeaders = (r) => r.headers;
const __connect_responseDebugContent = (r) => r.clone ().text ();
const __connect_responseFetch = (u, o) => { 
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'data') o.headers ['Content-Type'] = 'application/octet-stream';
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'text') o.headers ['Content-Type'] = 'text/plain';
  if (o.payload) o.body = o.payload, delete o.payload; 
  return __connect_fetch (u, o); 
}
const __connect_responseStatus = (r) => r.status;
const __connect_responseCheck = (r) => { if (!r.ok) throw Error (`__connect_error: ${r.status} ${r.statusText}`); }
const __connect_responseDecode = (r, t) => { const f = {
    'arraybuffer': (r) => r.arrayBuffer (),
    'blob': (r) => r.blob (),
    'json': (r) => r.json (),
    'xml' : (r) => __xml_parse (r.text ()),
    'text': (r) => String (r.text ()),
    'data': (r) => new Uint8Array (r.arrayBuffer ())
  } [t]; return f ? f (r) : undefined;
}

function __xml_parse (text) {
  throw 'xml parsing not implemented';
}

/*
CODE:GCLOUD */

const __connect_responseDebugHeaders = (r) => r.getAllHeaders ();
const __connect_responseDebugContent = (r) => r.getContentText ();
const __connect_responseFetch = (u, o) => {
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'data') o.headers ['Content-Type'] = 'application/octet-stream';
  if (o.headers ['Content-Type'] && o.headers ['Content-Type'] == 'text') o.headers ['Content-Type'] = 'text/plain';
  return UrlFetchApp.fetch (u, o);
}
const __connect_responseStatus = (r) => r.getResponseCode ();
const __connect_responseCheck = (r) => { }
const __connect_responseDecode = (r, t) => { const f = {
    'arraybuffer': (r) => util_data_to_arraybuffer (r.getBlob ().getBytes ()),
    'blob': (r) => r.getBlob (),
    'json': (r) => JSON.parse (r.getContentText ()),
    'xml' : (r) => __xml_parse (r.getContentText ()),
    'text': (r) => r.getContentText (),
    'data': (r) => r.getContent (),
  } [t]; return f ? f (r) : undefined;
}

function __xml_parse (text) {
  if (text.includes ('<') && text.includes ('>'))
    if (!util_is_null (text = XmlService.parse (text)))
      return text.getRootElement (); // might be undefined
  return undefined;
}

/* CODE:GCLOUD
*/

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function util_obj_property_mixin (Class, From) { for (const name of Object.getOwnPropertyNames (From.prototype)) if (name !== 'constructor')
  Object.defineProperty (Class.prototype, name, { ...Object.getOwnPropertyDescriptor (From.prototype, name), enumerable: true }); }

// -----------------------------------------------------------------------------------------------------------------------------------------

function __sync_fetch_runner () {
  process.stdin.__data = Array ();
  process.stdin.resume ();
  process.stdin.setEncoding ('utf8');
  process.stdin.on ('data', (chunk) => process.stdin.__data.push (chunk));
  process.stdin.on ('end', () => {
    const __error = ({ constructor, message, type, code }) => [ constructor.name, [message, type, { code }] ];
    const __content = (content) => Buffer.from (content).toString ('base64');
    const __buffer = (buffer) => Uint8Array.from (buffer).buffer;
    const __request = (resource, init) => new Request (resource, { ...init, body: init.body ? __buffer (Buffer.from (init.body, 'base64')) : undefined });
    const __response = ({ url, status, statusText, redirected, headers }) => ({ url, status, statusText, redirected, headers: Object.fromEntries (headers.entries ()) });
    const recv_request = () => __request (...JSON.parse (process.stdin.__data.join ('')));
    const send_respond = (response) => process.stdout.write (JSON.stringify (response));
    fetch (recv_request ())
      .then (response => response.arrayBuffer ()
        .then (buffer => send_respond ([__content (buffer), __response (response), undefined]))
        .catch (error => send_respond ([undefined, __response (response), __error (error)])))
      .catch (error => send_respond ([undefined, undefined, __error (error)]));
  });
}

const __sync_fetch_config = {
  'FILENAME_RUNNER': '__sync_fetch_runner.js',
  'FUNCTION_RUNNER': __sync_fetch_runner
};

function __sync_fetch_runner_toString () {
  return ['#!/usr/bin/env node', `${__sync_fetch_config.FUNCTION_RUNNER.toString ()} ();`, ''].join ('\n'); }

__gcloudrun_contentsInclude (__sync_fetch_config.FILENAME_RUNNER, 'application/javascript', __sync_fetch_runner_toString);

/* CODE:GCLOUD

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

function sync_fetch (resource, init) {
  const __execute = require ('child_process').execFileSync;
  const __running = [ [__dirname, __sync_fetch_config.FILENAME_RUNNER].join ('/') ];
  const __process = (input) => __execute (process.execPath, __running, { windowsHide: true, maxBuffer: Infinity, input, shell: false }).toString ();

  const __process_body = (body) => SyncFetchBody.__parse (body).toString ('base64');
  const __process_head = (head) => Object.fromEntries ((new Headers (head)).entries ());

  const request = [resource, { }]; Object.assign (request [1], init);
  if (request [1].body) request [1].body = __process_body (request [1].body);
  if (request [1].headers) request [1].headers = __process_head (request [1].headers);

  const response = JSON.parse (__process (JSON.stringify (request)));
  if (! response [1] || ! 'headers' in response [1])
    throw SyncFetchError.__deserialize (...response [2]);
  return SyncFetchResponse.__deserialize (...response);
}

// -----------------------------------------------------------------------------------------------------------------------------------------

class SyncFetchError extends Error {
  static __deserialize (name, init) {
    const errors = { TypeError }; return (name in errors) ? new errors [name] (...init) : new SyncFetchError (...init); }

  constructor (details) { super (details); }
}

class SyncFetchResponse {
  static __deserialize (body, init, error) {
    const bodyBuffer = body ? Buffer.from (body, 'base64') : undefined, bodyError = error ? SyncFetchError.__deserialize (...error) : undefined;
    const __headers = (p = {}) => { const h = new Headers (); for (const n in p) for (const v of p [n]) h.append (n, v); return h; }
    return new SyncFetchResponse ({ ...init, headers: __headers (init.headers) }, { bodyBuffer, bodyError }); }

  constructor (init, { bodyBuffer, bodyError }) { Object.assign (this, init);
    this.bodyBuffer = bodyBuffer, this.bodyError = bodyError; }
  clone () { this.__check (); const __clone = ({ url, headers, status, statusText, redirected }) => ({ url, headers, status, statusText, redirected });
    return new SyncFetchResponse (__clone (this), { bodyBuffer: Buffer.from (this.bodyBuffer), bodyError: this.bodyError });
  }
}

class SyncFetchBody {
  static __parse (body) {
    if (body == null) return null;
    if (Buffer.isBuffer (body)) return body;
    if (Object.prototype.toString.call (body) === '[object ArrayBuffer]') return Buffer.from (body);
    if (ArrayBuffer.isView (body)) return Buffer.from (body.buffer, body.byteOffset, body.byteLength);
    if (typeof body == 'string') return Buffer.from (String (body));
    throw new TypeError (`sync_fetch does not support bodies of type: ${type}`); }

  __check () { if (this.bodyError) throw this.bodyError; }
  __consume () { this.__check (); return this.bodyBuffer || Buffer.alloc (0); }

  arrayBuffer () { const buf = this.__consume (); return buf.buffer.slice (buf.byteOffset, buf.byteOffset + buf.byteLength); }
  text () { return this.__consume ().toString (); }
  json () { const buf = this.__consume (); try { return JSON.parse (buf.toString ()); } catch (err) { throw new SyncFetchError (`invalid json response at ${this.url}: ${err.message}`); } }
  buffer () { return Buffer.from (this.__consume ()); }
}

util_obj_property_mixin (SyncFetchResponse, SyncFetchBody);

// -----------------------------------------------------------------------------------------------------------------------------------------
// -----------------------------------------------------------------------------------------------------------------------------------------

CODE:GCLOUD */
```

**Comment by larsgw** [comment]
I think I've fixed the transfer of binary buffers. It's not the most efficient fix but I think it works.
