### ISSUE TITLE
Commas are being inserted into request string when request length is longer than one chunk

### ISSUE THREAD

**Issue by da70** [larsgw/sync-fetch#6]
The code in worker.js that reads in the user's HTTP request has a bug in it that causes commas to be inserted in between chunks of the message -- https://github.com/larsgw/sync-fetch/blob/ccf55a4f4c18b04d59ea9dca2dd1a86a83f08f20/worker.js#L14-#L15:

```JavaScript
process.stdin.on('end', function () {
  const input = JSON.parse(chunks.join())
```

`Array.prototype.join` will use a comma for the separator if no separator is specified.  In order to join the array elements into a string without any separator, an empty string must be passed in as the separator argument:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join:

> **_separator_** Optional
> Specifies a string to separate each pair of adjacent elements of the array. The separator is converted to a string if necessary. If omitted, the array elements are separated with a comma (","). If separator is an empty string, all elements are joined without any characters in between them.

I will submit a PR.  Just wanted to open this ticket for reference.

**Comment by larsgw** [comment]
Released in `v0.2.1`
